const req = {
  id: "false_553172532104@c.us_7A043CA59646B51AFFC6FDE7A09D6BD7",
  viewed: false,
  body: "X-Burguer\nR$ 23,00",
  type: "list_response",
  t: 1713293784,
  notifyName: "Marcelo Henrique",
  from: "553172532104@c.us",
  to: "554891487526@c.us",
  self: "in",
  ack: 1,
  invis: false,
  isNewMsg: true,
  star: false,
  kicNotified: false,
  recvFresh: true,
  isFromTemplate: false,
  pollInvalidated: false,
  isSentCagPollCreation: false,
  latestEditMsgKey: null,
  latestEditSenderTimestampMs: null,
  quotedMsg: {
    type: "list",
    list: {
      $$unknownFieldCount: 0,
      sections: [Array],
      description:
        "Seu pedido:\n" +
        "> Coca-Cola Lata x1\n" +
        "> Guaraná Lata x3\n" +
        "> Coca-Cola 2L x1\n" +
        "\n" +
        "Selecione umas das opções\n" +
        "* `Inclua mais itens`\n" +
        "\n" +
        "* `Finalizar e incluir adicionais`\n" +
        "\n" +
        "* `Ou selecione editar ou finalizar pedido`",
      buttonText: "Ver Cardápio 🍔",
      listType: 1,
    },
  },
  quotedStanzaID: "3EB0FBD1071EC262533217",
  quotedParticipant: "554891487526@c.us",
  mentionedJidList: [],
  groupMentions: [],
  isEventCanceled: false,
  isVcardOverMmsDocument: false,
  hasReaction: false,
  listResponse: {
    $$unknownFieldCount: 0,
    title: "X-Burguer",
    listType: 1,
    singleSelectReply: { $$unknownFieldCount: 0, selectedRowId: "1" },
    description: "R$ 23,00",
  },
  productHeaderImageRejected: false,
  lastPlaybackProgress: 0,
  isDynamicReplyButtonsMsg: false,
  isCarouselCard: false,
  parentMsgId: null,
  isMdHistoryMsg: false,
  stickerSentTs: 0,
  isAvatar: false,
  lastUpdateFromServerTs: 0,
  invokedBotWid: null,
  bizBotType: null,
  botResponseTargetId: null,
  botPluginType: null,
  botPluginReferenceIndex: null,
  botPluginSearchProvider: null,
  botPluginSearchUrl: null,
  botPluginMaybeParent: false,
  botReelPluginThumbnailCdnUrl: null,
  botMsgBodyType: null,
  requiresDirectConnection: false,
  chatId: "553172532104@c.us",
  fromMe: false,
  sender: {
    id: "553172532104@c.us",
    name: "Marcelo Henrique",
    shortName: "Marcelo Henrique",
    pushname: "Marcelo Henrique",
    type: "in",
    verifiedName: "Marcelo Henrique",
    isBusiness: true,
    isEnterprise: false,
    verifiedLevel: 0,
    privacyMode: null,
    isContactSyncCompleted: 1,
    textStatusLastUpdateTime: -1,
    formattedName: "Marcelo Henrique",
    isMe: false,
    isMyContact: true,
    isPSA: false,
    isUser: true,
    isWAContact: true,
    profilePicThumbObj: { eurl: null, id: "553172532104@c.us", tag: null },
    msgs: null,
  },
  timestamp: 1713293784,
  content: "X-Burguer\nR$ 23,00",
  isGroupMsg: false,
  quotedMsgId: "true_553172532104@c.us_3EB0FBD1071EC262533217",
  mediaData: {},
  platform: "wppconnect",
  interaction: "adicionais",
};
